use_frameworks!

platform :ios, '13.0'


source 'https://github.com/Garenge/pengpengSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'PPSocket_Example' do
  pod 'PPSocket', :path => '../'

  target 'PPSocket_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = '$(ARCHS_STANDARD)'
      config.build_settings['VALID_ARCHS'] = 'arm64 arm64e x86_64'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
